### PR TITLE
JSON output file in SonarQube format

### LINKED ISSUE #370: Integrate huskyCI with Sonar
It would be great to create a logic to input huskyCI output into [Sonar](https://www.sonarqube.org/). 

A good start would be looking at this JSON format from [Sonar Docs](https://docs.sonarqube.org/latest/analysis/generic-issue/).

### PR DESCRIPTION
**Pull request by joserenatosilva**
### Closes #370 
---
 
This PR aims to enable the huskyCI-client to create a JSON output file compatible with [Sonarqube generic issue](https://docs.sonarqube.org/latest/analysis/generic-issue/) importation. As it is, every execution creates/overwrites a json file named `result.json` inside a folder `huskyCI` created in the current working directory.

### CODE REVIEW

**Comment by mdjunior** [comment]
Hey @joserenatosilva,

This PR is a great contribution, but could you add some tests for the new functions (`generateSonarOutput`)?
Could the outputs be a separate package? This may facilitate testing and add new possibilities in the future.

Could you add a wiki page explaining how this integration can be done?

**Comment by joserenatosilva** [comment]
@mdjunior Sure, I'll change the PR to WIP, refactor and create some tests. 
To integrate I followed the documentation found [here](https://docs.sonarqube.org/latest/analysis/generic-issue/). I didn't test it directly with Sonarqube since our output maps every required field but I'll do it to create a wiki page on how to integrate with Sonarqube.

**Comment by joserenatosilva** [comment]
@mdjunior the wiki page still missing, but I updated the CLI client (added spotbugs, gitleaks and sonarqube integration).
I merged the master branch here (to update the security tests - spotbugs and gitleaks) so the number of files to review grew too much. I'll list here the files you need to check/review (files that I changed):

**CLI Update**
----
```
cli/client/print.go
cli/cmd/run.go
```

**SonarQube Update**
----
```
client/cmd/main.go
client/util/*
client/testdata/*
client/integration/sonarqube/*
```

I'll test the SonarQube integration manually and report back.

**Comment by joserenatosilva** [comment]
It looks like SonarQube always needs an existing file and a valid line number, how do we approach our low vulnerability indicating that no requirements.txt, yarn.lock or package.json file is missing? Create an empty file and point line 1? I need to fix that, so I'll move back to WIP

**Comment by joserenatosilva** [comment]
As it is now the client creates a file named `sonarqube.json` inside a folder named `./huskyCI/` (this is hardcoded inside `client/cmd/main.go`).

Regarding my last commentary:
> It looks like SonarQube always needs an existing file and a valid line number, how do we approach our low vulnerability indicating that no requirements.txt, yarn.lock or package.json file is missing? Create an empty file and point line 1? I need to fix that, so I'll move back to WIP

There are more problems with missing files, in case of vulnerable dependencies, the security tools don't report an associated file and its line (requirements.txt, yarn.lock, package-lock.json, etc.). Aiming to solve all of the missing files cases I created a check that verifies if there's no file associated with a given vulnerability and creates a placeholder file with content:

```
Placeholder file indicating that no file was associated with this vulnerability.
This usually means that the vulnerability is related to a missing file
or is not associated with any specific file, i.e.: vulnerable dependency versions.
```

The SonarQube integration won't work correctly locally with our generated `.env` file. The file being generated right now looks like:

```sh
export HUSKYCI_CLIENT_REPO_URL="https://github.com/globocom/huskyCI.git"
export HUSKYCI_CLIENT_REPO_BRANCH="vulns-Golang"
export HUSKYCI_CLIENT_API_ADDR="http://localhost:8888"
export HUSKYCI_CLIENT_API_USE_HTTPS="false"
export HUSKYCI_CLIENT_TOKEN="HUSKYCITOKEN"
```

As we execute the sonar-scanner with: `sonar-scanner   -Dsonar.projectKey=$PROJECT_KEY   -Dsonar.sources=.   -Dsonar.host.url=$SONAR_URL   -Dsonar.login=$SONAR_TOKEN -Dsonar.externalIssuesReportPaths=./huskyCI/sonarqube.json`, as is specified in `sonar.sources=.`, SonarQube looks for files in the current working directory but since we can specify a different HUSKYCI_CLIENT_REPO_BRANCH from the source code in the working directory or even a completely different HUSKYCI_CLIENT_REPO_URL the command line won't work.

It should work in a CI context since the container should have the current code/branch inside the pipeline. @mdjunior, @rafaveira3 How should we approach this local SonarQube execution?

**Comment by rafaveira3** [comment]
Hey, @joserenatosilva! This is a great contribution! 🚀 Thanks a lot for your time and effort in working on this one. As we do not use Sonar in our local environment (via docker-compose, for example), we can think about this in another moment. It would be great if we focus on the CI context. 🙃

**Pull request merged**
